tag_index:
    path:     /
    defaults: { _controller: "PortfolioBundle:Tag:index" }
    methods:  GET

tag_show:
    path:     /{id}/show
    defaults: { _controller: "PortfolioBundle:Tag:show" }
    methods:  GET

tag_new:
    path:     /new
    defaults: { _controller: "PortfolioBundle:Tag:new" }
    methods:  [GET, POST]

tag_edit:
    path:     /{id}/edit
    defaults: { _controller: "PortfolioBundle:Tag:edit" }
    methods:  [GET, POST]

tag_delete:
    path:     /{id}/delete
    defaults: { _controller: "PortfolioBundle:Tag:delete" }
    methods:  DELETE
