<?php

namespace PortfolioBundle\Repository;

/**
 * CitationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CitationRepository extends \Doctrine\ORM\EntityRepository
{
}
