<?php

namespace PortfolioBundle\Repository;
use Doctrine\ORM\EntityRepository as entityRepo;

/**
 * CitationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CitationRepository extends entityRepo
{
    public function getRecordCount() { //fonction qui compte le nombre d'entrée dans la table
        return ( $this->createQueryBuilder('q')
            ->select('count(q.id)')
            ->getQuery()
            ->getSingleScalarResult()
        );
    }

    public function getRandomQuote() {

        $total = $this->getRecordCount();
        $randResult = rand(0, $total - 1); // -1 parce qu'on commence à 0

        $qb = $this->createQueryBuilder('q')
            ->select('q')
            ->setMaxResults(1)
            ->setFirstResult($randResult)
            ->getQuery();

        return $qb->getResult();


    }


}
