<?php

namespace PortfolioBundle\Repository;

/**
 * CultureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CultureRepository extends \Doctrine\ORM\EntityRepository
{
}
